gui:
  border: rounded
  theme:
    activeBorderColor:
      - '#fab387'
      - bold
    inactiveBorderColor:
      - '#7f849c' # '#a6adc8'
    searchingActiveBorderColor:
      - '#f9e2af'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - '#fab387'
    cherryPickedCommitBgColor:
      - '#45475a'
    markedBaseCommitFgColor:
      - '#fab387'
    markedBaseCommitBgColor:
      - '#45475a'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#bac2de' # '#cdd6f4'
  authorColors:
    '*': '#b4befe'

git:
  paging:
    colorArg: always
    pager: delta --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
