#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai_config=(
  layout                    bsp
  top_padding               10
  bottom_padding            10
  left_padding              13
  right_padding             13
  window_gap                10
  auto_balance              off
  mouse_follows_focus       off
  focus_follows_mouse       autofocus
  window_placement          second_child
  window_shadow             off
  insert_feedback_color     0xffbabbf1
)

yabai -m config ${yabai_config[*]}

yabai -m space 1 --label fun 
yabai -m space 2 --label left 
yabai -m space 3 --label main
yabai -m space 4 --label right
yabai -m space 5 --label chat
yabai -m space 6 --label music

yabai -m rule --add app="^(Messages|Mail|Outlook|Calculator|Software Update|Dictionary|System Preferences|System Settings|Photo Booth|Archive Utility|App Store|Activity Monitor|Clock|Preview|Font Book)$" manage=off
yabai -m rule --add app="^Arc$" title="^Space [0-9]+$|ybf$" manage=off
yabai -m rule --add app="^(Karabiner-Elements|Karabiner-EventViewer|HTTPie|Postman|Clash Verge|SwitchHosts|Docker Desktop| Microsoft Teams)$" manage=off

yabai -m rule --add app="^(Arc)$" manage=off space=left
yabai -m rule --add app="^(WezTerm|Rider|DataGrip)$" space=main
yabai -m rule --add app="^(Discord|Microsoft Teams)$" space=chat
yabai -m rule --add app="^(Spotify)$" space=music

yabai -m space --focus main

yabai -m rule --apply

borders active_color=0xff8087a2 inactive_color=0xff494d64 width=5.0 &
echo "yabai configuration loaded.."
