#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai_config=(
  layout                    bsp
  top_padding               10
  bottom_padding            10
  left_padding              13
  right_padding             13
  window_gap                10
  auto_balance              off
  mouse_follows_focus       off
  focus_follows_mouse       off
  window_placement          second_child
  window_shadow             off
  insert_feedback_color     0xffbabbf1
)

yabai -m config ${yabai_config[*]}

# -- Space preparing ---------------------------------------------------------------------------------------------------

function space_destroy_amount {
  for idx in $(yabai -m query --spaces | jq ".[].index | select(. > $1)" | sort -nr); do
    yabai -m space --destroy "$idx"
  done
}

function space_create {
  local display=$(display_index_get $1) local idx=$2
  local name=$3
  local space=$(yabai -m query --spaces | jq "first(.[] | select(.index == $idx) | .index)")

  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name" --display "$display"
}

space_destroy_amount 10

# Space Configuration
# ------------------
# Format: space_create <display_number> <space_index> <space_label>
# Display 1 (Primary):
#   Spaces 1-8: Daily workflow organization
# Display 2 (Secondary):
#   Space 9: Dedicated browser space
#

space_create 1 1 social
space_create 1 2 devBrowser
space_create 1 3 term
space_create 1 4 tasks
space_create 1 5 calls
space_create 1 6 email
space_create 1 7 music
space_create 1 8 design
space_create 1 9 documents
space_create 2 10 browser

yabai -m rule --add space=social app="^(Discord|Telegram|Toggl Track)$"
yabai -m rule --add app="^Arc$" title="^Space 1$" space=devBrowser
yabai -m rule --add space=term app="^(WezTerm|VSCode|JetBrains Rider)$"
yabai -m rule --add app="^Arc$" title="^Space 2$" space=browser
yabai -m rule --add space=tasks app="^(Things|Notion Calendar|Amie)$"
yabai -m rule --add space=music app="^(Spotify)$"
yabai -m rule --add space=documents app="^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Acrobat)$"
yabai -m rule --add space=design app="^(Figma|Miro)$"
yabai -m rule --add space=calls app="^Microsoft Teams|Teams)$"
yabai -m rule --add space=email app="^(Mail|Microsoft Outlook)$"

# disable specific apps
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Bartender 5$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^(Messages|Mail|Outlook|Calculator|Software Update|Dictionary|System Preferences|System Settings|Photo Booth|Archive Utility|App Store|Activity Monitor|Clock|Preview|Font Book|Notes)$" manage=off
# yabai -m rule --add app="^Arc$" title="^Space [0-9]+$|ybf$" manage=off
yabai -m rule --add app="^(Karabiner-Elements|Karabiner-EventViewer|HTTPie|Postman|Clash Verge|SwitchHosts|Docker Desktop)$" manage=off
yabai -m rule --add app="^(Microsoft Teams)$" title="^(Microsoft Teams meeting)$" manage=off

# yabai -m rule --add app="^(Arc)$" manage=off space=left
# yabai -m rule --add app="^(WezTerm|JetBrains Rider)$" space=main
# yabai -m rule --add app="^(JetBrains DataGrip)$" manage=off space=right
# yabai -m rule --add app="^(Discord|Microsoft Teams|Outlook)$" manage=off space=chat
# yabai -m rule --add app="^(Spotify)$" space=music

yabai -m space --focus main

yabai -m rule --apply

borders active_color=0xff8087a2 inactive_color=0xff494d64 width=5.0 &
echo "yabai configuration loaded.."
