#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/wiki/Commands
# Layout Controls (cmd + ctrl + shift + alt):
#   - b : bsp (tiled) layout
#   - s : stack layout
#   - r : rotate 180°
#   - 0 : balance windows
#   - f : toggle fullscreen

cmd + ctrl + shift + alt - b : yabai -m space --layout bsp
cmd + ctrl + shift + alt - s : yabai -m space --layout stack
cmd + ctrl + shift + alt - r : yabai -m space --rotate 180
cmd + ctrl + shift + alt - 0 : yabai -m space --balance
cmd + ctrl + shift + alt - f : yabai -m window --toggle zoom-fullscreen

# Stack Navigation: ctrl + {↑, ↓}
# ctrl - down : yabai -m window --focus stack.next
# ctrl - up : yabai -m window --focus stack.prev

# ctrl - left : yabai -m space --focus next || yabai -m space --focus first
# ctrl - right : yabai -m space --focus prev || yabai -m space --focus last

# alt + ctrl - x : yabai -m space --mirror x-axis
# alt + ctrl - y : yabai -m space --mirror y-axis

# Window Movement (cmd):
#   - ←→↑↓ : move window in direction or to next display
cmd - left  : yabai -m window --warp west || $(yabai -m window --display west && yabai -m display --focus west && yabai -m window --warp last)
cmd - down  : yabai -m window --warp south || $(yabai -m window --display south && yabai -m display --focus south)
cmd - up    : yabai -m window --warp north || $(yabai -m window --display north && yabai -m display --focus north)
cmd - right : yabai -m window --warp east || $(yabai -m window --display east && yabai -m display --focus east && yabai -m window --warp first)

# Resize windows: alt - {←, →, ↑, ↓}
alt - left : yabai -m window --resize left:-100:0 || yabai -m window --resize right:-100:0
alt - down : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
alt - up : yabai -m window --resize top:0:-100 || yabai -m window --resize bottom:0:-100
alt - right : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# Window Navigation (through display borders): alt + ctrl - {h, j, k, l}
alt + ctrl - h : yabai -m window --focus west || yabai -m display --focus west
alt + ctrl - j : yabai -m window --focus south || yabai -m display --focus south
alt + ctrl - k : yabai -m window --focus north || yabai -m display --focus north
alt + ctrl - l : yabai -m window --focus east || yabai -m display --focus east

# toggle float window
alt + ctrl - f : yabai -m window --toggle float --grid 10:8:1:1:6:8

# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
alt + ctrl - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}" && \
                  yabai -m space --layout bsp

# destroy space 
alt + ctrl - s : yabai -m space --destroy

alt + ctrl - v : yabai -m window --toggle split

# reboot Yabai
alt + ctrl - r : /usr/bin/env osascript <<< "display notification \"Yabai is reloading\" with title \"Yabai\""; \
                 launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# space
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9

alt + ctrl - 1 : yabai -m window --space 1 --focus
alt + ctrl - 2 : yabai -m window --space 2 --focus
alt + ctrl - 3 : yabai -m window --space 3 --focus
alt + ctrl - 4 : yabai -m window --space 4 --focus
alt + ctrl - 5 : yabai -m window --space 5 --focus
alt + ctrl - 6 : yabai -m window --space 6 --focus
alt + ctrl - 7 : yabai -m window --space 7 --focus
alt + ctrl - 8 : yabai -m window --space 8 --focus
alt + ctrl - 9 : yabai -m window --space 9 --focus
