#!/usr/bin/env zsh

fpath=($ZDOTDIR/.zsh/plugins $fpath)

# ZSH only and most performant way to check existence of an executable
exists() { (( $+commands[$1] )); }

# disable vi mode
bindkey -e

# history
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=$ZSH_CACHE_DIR/zsh_history

# alias
alias zj=zellij
alias lg=lazygit

if exists zoxide; then
  eval "$(zoxide init zsh)"
fi

if exists starship; then
  eval "$(starship init zsh)"
fi

# +----------+
# | worktree |
# +----------+
source $ZDOTDIR/.zsh/plugins/zsh-git-worktree/zsh-git-worktrees.zsh

# +-------+
# | alias |
# +-------+
source $ZDOTDIR/.zsh/scripts/aliais.zsh

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # make lowercase tab-complete case insensitive


# COMPLETIONS
FPATH=$HOME/.zsh/completions:$FPATH
if type brew &>/dev/null; then
	FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi
autoload -Uz compinit && compinit

# AZURE CLI
if type az &>/dev/null; then
  autoload bashcompinit && bashcompinit
  source $(brew --prefix)/etc/bash_completion.d/az
fi

# KUBECTL
if type kubectl &>/dev/null; then
  source <(kubectl completion zsh)
fi

if exists fzf; then
  source <(fzf --zsh)
fi

